import { Inter } from 'next/font/google'
import '../globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Design Site',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        {children}
      </body>
    </html>
  );
  
}
